### ISSUE TITLE
Python 2 not yet supported

### ISSUE THREAD

**Issue by jayvdb** [Ousret/charset_normalizer#1]
```py
Traceback:
test/test_on_file.py:5: in <module>
    from charset_normalizer import CharsetNormalizerMatches as CnM
charset_normalizer/__init__.py:2: in <module>
    from charset_normalizer.normalizer import CharsetNormalizerMatches, CharsetNormalizerMatch
charset_normalizer/normalizer.py:3: in <module>
    import statistics
E   ImportError: No module named statistics
```

**Comment by jayvdb** [comment]
Also seen on https://travis-ci.org/Ousret/charset_normalizer/jobs/577468690

There is a `statistics` backport which can be required only on py2.

After that, the next py2 problem is `ImportError: cannot import name lru_cache`

**Comment by jayvdb** [comment]
And then

`AttributeError: 'str' object has no attribute 'isprintable'`

and


```py
File "../charset_normalizer/normalizer.py", line 239, in from_bytes
    str(sequences, encoding=p)
TypeError: str() takes at most 1 argument (2 given)
```

And test_should_be_accented failing for some reason.

**Comment by jayvdb** [comment]
'isprintable' is the hard one ... it will require a backport of py3 unicode to py2.  There are a few of them - I used one in about 2015, but I suspect they may not be maintained very well as the usefulness and usage reduced.

**Comment by jayvdb** [comment]
https://pypi.org/project/unicodedata2/ is the one I was thinking about ; not sure it has isprintable .  maybe need `future` for that?

**Comment by Ousret** [comment]
Hi,

I've tried the same and stopped at `isprintable` method support. 
I'm looking/considering bulding my own isprintable method and add it to unicode helper class.

**Comment by jayvdb** [comment]
https://github.com/PythonCharmers/python-future/blob/b7fd8a50117a1eb9126ca8840e2b4c4a5c5f70bf/src/future/types/newstr.py#L414 `raise NotImplementedError('fixme')` :/

**Comment by Ousret** [comment]
See #5
