### ISSUE TITLE
[Comment] Alpine, AOSC, and Spack packages

### ISSUE THREAD

**Issue by BoboTiG** [Ousret/charset_normalizer#123]
Hey @Ousret,

In order to be able to ship HTTPie 2.6.0, I needed to provide `charset-normalizer` packages for Alpine Linux, AOSC, and Spack.
It is just a small word to let you know, nothing else. On other platforms, the module was already present though :)

FTR, there are pull requests:

- Alpine: https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/26449
- AOSC: https://github.com/AOSC-Dev/aosc-os-abbs/pull/3568
- Spack: https://github.com/spack/spack/pull/26756

Thank you for the easy installation requirements (and the whole module itself, indeed) :champagne:

**Comment by Ousret** [comment]
Thanks for the heads-up. 
You are quite welcome.
