### ISSUE TITLE
Issues with encodings used in the Baltics

### ISSUE THREAD

**Issue by adbar** [Ousret/charset_normalizer#130]
**Describe the bug**

- ISO-8859-15 detected correctly by chardet and cchardet, charset_normalizer says cp850,cp857,cp858
- WINDOWS-1252 detected correctly by chardet and cchardet, charset_normalizer says cp775,cp850,cp857,cp858

The language detection works in both cases (Estonian).

**To Reproduce**
- https://gitlab.freedesktop.org/uchardet/uchardet/-/blob/master/test/et/iso-8859-15.txt
- https://gitlab.freedesktop.org/uchardet/uchardet/-/blob/master/test/et/windows-1252.txt

**Desktop (please complete the following information):**

https://charsetnormalizerweb-ousret.vercel.app/

**Comment by Ousret** [comment]
I have pushed/merged a solid patch for one of the two cases you presented me.

For the remaining file, I could not find a viable solution for now. It still produces some very readable Estonian.
https://gitlab.freedesktop.org/uchardet/uchardet/-/blob/master/test/et/iso-8859-15.txt

Feel free to check against dev-master@2.0.8.dev1

**Comment by adbar** [comment]
Nice, thanks!
