### ISSUE TITLE
Copyright status of test data

### ISSUE THREAD

**Issue by stefanor** [Ousret/charset_normalizer#138]
Can you clarify the copyright status of the test data files in `data`? There are some things there that look like commercial TV subtitles. I wouldn't assume that you can legally redistribute those.

This came up when reviewing the package contents in Debian.

Ideally, anything that is public domain or freely licensed should be documented with the copyright holder and license. And everything else should be removed from the package. That's a fairly tireless bureaucratic job, but it needs to be done for us to be able to distribute the test content and run the test suite.

**Comment by stefanor** [comment]
FYI: @natureshadow

**Comment by Ousret** [comment]
I can clarify. First of all, I am not a legal expert.
Those freely available subtitles are indeed for _commercial TV shows_. The SRTs are not attached to any licenses that I am aware of. Neither they are extracted from copyrighted material, my understanding is they are made from scratch by the respective authors mentioned in them.

I have done some research and never found something very clear about the current use case.
More on that, you may find interesting the ongoing issue https://github.com/chardet/chardet/issues/231 

> Regarding CC-BY-SA: in a first reaction, our licensing expert agreed that he also wouldn't see chardet code as derived work of a CC-BY-SA testsuite file. He however pointed out a future risk when specific content in the testsuite (think of a very rare combination of encodings in a test sample?) triggers a special feature or bugfix in chardet code. No idea whether such a scenario is realistic...

Ideally, I could get rid of them, but not in a short term.
Legally speaking I don't see anything hard-blocking. Can you seek legal advice from an expert? Having a good explanation would help.

**Comment by stefanor** [comment]
> Those freely available subtitles are indeed for commercial TV shows. The SRTs are not attached to any licenses that I am aware of. Neither they are extracted from copyrighted material, my understanding is they are made from scratch by the respective authors mentioned in them.

Copyright law of course varies from jurisdiction to jurisdiction, but my understanding would be that subtitles are a derivative of the TV shows. Both the translator and the producers of the series would have a copyright interest. They may be freely available on the Internet, but that doesn't mean that they are being legally distributed on the Internet. It's more of a grey area that isn't being policed.

Here's an article confirming this interpretation in court in the Netherlands: https://fossbytes.com/are-subtitles-illegal/

> Ideally, I could get rid of them, but not in a short term.

It seems that in the short term, we're just shipping them, too. But it's definitely not ideal.

> Can you seek legal advice from an expert?

I'm afraid I don't have any council I can reach to on this, but I could ask on the debian-legal mailing list, where I expect to hear many people saying the same thing.

**Comment by Ousret** [comment]
I had the chance to reach someone with a legal background, the conclusion is: some countries clearly stated those as unauthorized either in their laws or courts. So in the light of those, I will prioritize the removal/replacement of the targeted assets.
