### ISSUE TITLE
[BUG] 2.0.8 way too verbose

### ISSUE THREAD

**Issue by fenchu** [Ousret/charset_normalizer#145]
```
>>> import requests
>>> requests.__version__
'2.26.0'
>>> import charset_normalizer
>>> charset_normalizer.__version__
'2.0.8'
```

windows10, ubuntu 20.04 lts

I need to set this in all files just to get rid of it:
```
logging.getLogger('charset_normalizer').setLevel(logging.FATAL)
```

the first and the last are mine, in the middle just hyper verbose, definetely not info, not even debug.
```
20211125112541|INFO|operator users:{'username': '15918697710', 'phone': '+4799113717', 'personstatus': 'bosatt', 'fornavn': 'VIS', 'mellomnavn': None, 'etternavn': 'FORDYPNING'}

20211125112541|WARNING|override steps (5) and chunk_size (512) as content does not fit (465 byte(s) given) parameters.
20211125112541|INFO|ascii passed initial chaos probing. Mean measured chaos is 0.000000 %
20211125112541|INFO|ascii should target any language(s) of ['Latin Based']
20211125112541|INFO|We detected language [('English', 1.0), ('Dutch', 1.0), ('Indonesian', 1.0)] using ascii
20211125112541|INFO|ascii is most likely the one. Stopping the process.
20211125112541|WARNING|override steps (5) and chunk_size (512) as content does not fit (465 byte(s) given) parameters.
20211125112541|INFO|ascii passed initial chaos probing. Mean measured chaos is 0.000000 %
20211125112541|INFO|ascii should target any language(s) of ['Latin Based']
20211125112541|INFO|We detected language [('English', 1.0), ('Dutch', 1.0), ('Indonesian', 1.0)] using ascii
20211125112541|INFO|ascii is most likely the one. Stopping the process.

20211125112541|INFO|added mobile: {'result': 0, 'description': 'success', 'dn': '', 'message': '', 'referrals': None, 'type': 'modifyResponse'}

```

**Comment by fenchu** [comment]
I do not use this package it is all from requests.py,

**Comment by Ousret** [comment]
While I understand your concern, I do not share it.
It is not a bug but rather a change request.

What I understand from your ticket is:
- You set up a custom handler for n lib
- You dislike the amount of generated entries given by `charset_normalizer`
- You manually changed the verbosity level to silent it

What happens to you is that your server does not give an explicit `charset` to decode the text/payload/JSON and requests will use this library to 'guess' the actual encoding.

Maybe I misunderstood your point, but the entries nor the levels applied changed between minor.

**Comment by fenchu** [comment]
I set explicitly "Content-Type: application/json; charset=utf-8" in all headers or downgrade to requests v 2.25.1 to fix this. 

But I really do not see any need for guessing the encoding, just crash if it fails, But this is a issue for requests.py team

thanks
