### ISSUE TITLE
[BUG] api.py "sequences: bytes" SyntaxError

### ISSUE THREAD

**Issue by nergalex** [Ousret/charset_normalizer#157]
**Describe the bug**
Error raised during module import:

```
  File \"/opt/custom-envs/cloudbuilder-k8s-py3/lib/python3.9/site-packages/requests/__init__.py\", line 48, in <module>
    from charset_normalizer import __version__ as charset_normalizer_version
  File \"/opt/custom-envs/cloudbuilder-k8s-py3/lib/python3.9/site-packages/charset_normalizer/__init__.py\", line 24, in <module>
    from .api import from_bytes, from_fp, from_path, normalize
  File \"/opt/custom-envs/cloudbuilder-k8s-py3/lib/python3.9/site-packages/charset_normalizer/api.py\", line 36
    sequences: bytes,
             ^
SyntaxError: invalid syntax
```

**To Reproduce**
- install Python 3.9.9
- use ansible collection kubernetes.core version 2.2.2
- run a task using kubernetes.core.k8s

**Logs**
[log.txt](https://github.com/Ousret/charset_normalizer/files/7799911/log.txt)

**Desktop (please complete the following information):**
 - OS: Red Hat Enterprise Linux Server release 7.9 (Maipo)
 - Python version: Python 3.9.9
 - Package version: 2.0.9

**Comment by Ousret** [comment]
Similarly to #114 I highly think that your Python setup is not in a good shape.
The SyntaxError on `sequences: bytes` means that your Python Core does not support type hint on function arguments.

**Comment by nergalex** [comment]
Thank you. Correct, error was python2 used instead of python3
