### ISSUE TITLE
UTF-8 file detects as 'ascii' is this normal? [DETECTION]

### ISSUE THREAD

**Issue by NebularNerd** [Ousret/charset_normalizer#197]
**Notice**
I hereby announce that my raw input is not :
- Too small content (<=32 characters) as I do know that ANY charset detector heavily depends on content
- Encoded in a deprecated/abandoned encoding that is not even supported by my interpreter

**Provide the file**
A accessible way of retrieving the file concerned. Host it somewhere with untouched encoding.
https://drive.google.com/file/d/1-qE5HG1AOKGl8-4R2eQQvhdvTN52mm9-/view?usp=sharing  

**Verbose output**
Using the CLI, run `normalizer -v ./my-file.txt` and past the result in here.
```
PS C:\CMDLINE\p> normalizer -v 'R:\08-05-22(ANSI).srt'
2022-06-24 20:57:59,218 | Level 5 | ascii passed initial chaos probing. Mean measured chaos is 0.000000 %
2022-06-24 20:57:59,218 | Level 5 | ascii should target any language(s) of ['Latin Based']
2022-06-24 20:57:59,218 | DEBUG | Encoding detection: ascii is most likely the one.
{
    "path": "R:\\08-05-22(ANSI).srt",
    "encoding": "ascii",
    "encoding_aliases": [
        "646",
        "ansi_x3.4_1968",
        "ansi_x3_4_1968",
        "ansi_x3.4_1986",
        "cp367",
        "csascii",
        "ibm367",
        "iso646_us",
        "iso_646.irv_1991",
        "iso_ir_6",
        "us",
        "us_ascii"
    ],
    "alternative_encodings": [],
    "language": "English",
    "alphabets": [
        "Basic Latin",
        "Control character"
    ],
    "has_sig_or_bom": false,
    "chaos": 0.0,
    "coherence": 0.0,
    "unicode_path": null,
    "is_preferred": true
}

******* Output from my script *******
Input file  :
 R:\08-05-22(ANSI).srt
Output file :
 R:\08-05-22(ANSI).txt

Detected Character Encoding: ascii
Confidence of encoding     : 100.00%
Output will use input encoding
```
```
PS C:\CMDLINE\p> normalizer -v 'R:\08-05-22(BOM-SIG).srt'
2022-06-24 20:59:23,682 | Level 5 | Detected a SIG or BOM mark on first 3 byte(s). Priority +1 given for utf_8.
2022-06-24 20:59:23,682 | Level 5 | Code page utf_8 is a multi byte encoding table and it appear that at least one character was encoded using n-bytes.
2022-06-24 20:59:23,689 | Level 5 | utf_8 passed initial chaos probing. Mean measured chaos is 0.000000 %
2022-06-24 20:59:23,693 | Level 5 | We detected language [('English', 1.0), ('Indonesian', 1.0), ('Simple English', 1.0), ('Dutch', 1.0), ('Norwegian', 1.0)] using utf_8
2022-06-24 20:59:23,693 | DEBUG | Encoding detection: utf_8 is most likely the one.
{
    "path": "R:\\08-05-22(BOM-SIG).srt",
    "encoding": "utf_8",
    "encoding_aliases": [
        "u8",
        "utf",
        "utf8",
        "utf8_ucs2",
        "utf8_ucs4",
        "cp65001"
    ],
    "alternative_encodings": [],
    "language": "English",
    "alphabets": [
        "Basic Latin",
        "Control character"
    ],
    "has_sig_or_bom": true,
    "chaos": 0.0,
    "coherence": 100.0,
    "unicode_path": null,
    "is_preferred": true
}

******* Output from my script *******
Input file  :
 R:\08-05-22(BOM-SIG).srt
Output file :
 R:\08-05-22(BOM-SIG).txt

Detected Character Encoding: UTF-8-SIG
Confidence of encoding     : 100.00%
Output will use input encoding
```
```
PS C:\CMDLINE\p> normalizer -v 'R:\08-05-22.srt'
2022-06-24 20:59:50,665 | Level 5 | ascii passed initial chaos probing. Mean measured chaos is 0.000000 %
2022-06-24 20:59:50,666 | Level 5 | ascii should target any language(s) of ['Latin Based']
2022-06-24 20:59:50,666 | DEBUG | Encoding detection: ascii is most likely the one.
{
    "path": "R:\\08-05-22.srt",
    "encoding": "ascii",
    "encoding_aliases": [
        "646",
        "ansi_x3.4_1968",
        "ansi_x3_4_1968",
        "ansi_x3.4_1986",
        "cp367",
        "csascii",
        "ibm367",
        "iso646_us",
        "iso_646.irv_1991",
        "iso_ir_6",
        "us",
        "us_ascii"
    ],
    "alternative_encodings": [],
    "language": "English",
    "alphabets": [
        "Basic Latin",
        "Control character"
    ],
    "has_sig_or_bom": false,
    "chaos": 0.0,
    "coherence": 0.0,
    "unicode_path": null,
    "is_preferred": true
}

******* Output from my script *******
Input file  :
 R:\08-05-22.srt
Output file :
 R:\08-05-22.txt

Detected Character Encoding: ascii
Confidence of encoding     : 100.00%
Output will use input encoding
```

**Expected encoding**
08-05-22.srt should detect as UTF-8  

**Desktop (please complete the following information):**
 - OS: Win 10 x64
 - Python version: 3.10
 - Package version:  charset-normalizer 2.0.12

**Additional context**
I have switched over from cChardet as it unfortunately looks to have become no longer supported/updated. With cChartdet it would return UTF8 as the detected encoding for UTF8 files. With your code it returns 'ascii' as the detected encoding (this is the plain 08-05-22.srt in my zip). With a BOM/SIG encoded file it detects as UTF and calls it 'UTF-8-SIG' as cChardet did. Is 'ascii' the expected response to plain UTF8 files? The reason I use it is to set the encoding on a file read using:  
```
 with open(ifile, 'r', encoding=encoding) as original, open(ofile, 'w', encoding=encset) as new:
```
Where 'encoding' is the detected encoding, 'encset' is a flag that can force uft8 or the original encoding as desired. At present I am calling your module through your cChardet legacy 'encoding' support i.e.: ```print('Detected Character Encoding:',encoding)```

**Comment by Ousret** [comment]
Thanks for considering switching from cChardet to this solution. 
I have opened and checked your files.

The subtitles you presented us may be encoded from a UTF-8 encoder BUT there is no way to tell.

You see, UTF-8 is a strict superset of ASCII, every ASCII file could be considered UTF-8.
We could remove the 'ASCII' return but would be a breaking change in many aspects.

```python
"Hello World".encode("utf_8") == "Hello World".encode("ascii")  # return True
```

charset-normalizer WILL return UTF-8 if : 

- There is a SIG at the beginning of the file
- Contain at least ONE character that is not in the ASCII range

Many other character sets do inherit from ASCII.

Hope that answers the question.

**Comment by NebularNerd** [comment]
Thanks for confirming @Ousret,

I was thrown off by the SIG entry showing utf8 in the -v output. As you say in most cases it makes no odds, the key thing is what goes in and what comes out contains all correct characters. 🙂  

For my script it's used for testing if the subtitle file contain non-ascii characters (mainly for chinese, arabic etc..), this then sets the encode values for read and write to preserve (or fix) the encoding on the output. 

Thanks again for taking the time to reply 🙂
