### ISSUE TITLE
Continuous fuzzing by way of OSS-Fuzz

### ISSUE THREAD

**Issue by DavidKorczynski** [Ousret/charset_normalizer#210]
Hi,

I was wondering if you would like to integrate continuous fuzzing by way of OSS-Fuzz? Fuzzing is a way to automate test-case generation and can be used to find unexpected exceptions in Python. In this PR https://github.com/google/oss-fuzz/pull/8265 I did an initial integration into OSS-Fuzz and the [current fuzzer](https://github.com/google/oss-fuzz/pull/8265/files#diff-3b025ab661ac174b20269139158cdb7a05c4d7a556e7198ac727d891f2d7b8c7) simply targets `from_bytes`. The fuzzing engine used by OSS-Fuzz is [Atheris](https://github.com/google/atheris).

If you would like to integrate, the only thing I need is a list of email(s) that will get access to the data produced by OSS-Fuzz, such as bug reports, coverage reports and more stats. Notice the emails affiliated with the project will be public in the OSS-Fuzz repo, as they will be part of a configuration file.

**Comment by Ousret** [comment]
Hi,

I am not against it. I am not familiar with this solution but I understand its principles.
What I am concerned about is the ability of "OSS-Fuzz, Altheris" to find out the input types so the tests would be relevant to us.

> I need is a list of email(s) that will get access to the data produced by OSS-Fuzz, such as bug reports, coverage reports and more stats.

Take the one listed publicly on pypi https://pypi.org/project/charset-normalizer/
If this is spammy or too verbose, I will be forced to block it.

**Comment by DavidKorczynski** [comment]
Thank you @Ousret  It's now added on the OSS-Fuzz side.

I will keep an eye on how the fuzzer progresses and ensure code coverage is optimal!
