### ISSUE TITLE
[BUG] Incorrect Git tag for version 2.1.1

### ISSUE THREAD

**Issue by facutuesca** [Ousret/charset_normalizer#217]
**Describe the bug**
Currently, the [2.1.1](https://github.com/Ousret/charset_normalizer/tree/2.1.1) tag points to commit https://github.com/Ousret/charset_normalizer/commit/47c8e714accc5aa8a9446319a9a6f3f002f2e248. However, the version bump from `2.1.0` to `2.1.1` happened afterwards, in commit https://github.com/Ousret/charset_normalizer/commit/86cda88ce13c8456c229b7564c08fc98b44a7e95. Due to this, if one checks out tag `2.1.1` and installs the package, the installed package has the incorrect (`2.1.0`) version.

**To Reproduce**
```bash
git clone https://github.com/Ousret/charset_normalizer && cd charset_normalizer
git checkout 2.1.1
pip install .
# (....) Successfully installed charset-normalizer-2.1.0
```
**Expected behavior**
Version of installed package should match the tag (`2.1.1`)

**Additional context**
This can be fixed by rewriting the tag and pushing:
```bash
git tag --force 2.1.1 86cda88ce13c8456c229b7564c08fc98b44a7e95
git push --force --tags
```

**Comment by Ousret** [comment]
Thanks for the report, this is now resolved.
