### ISSUE TITLE
[BUG] requests depend solving failed

### ISSUE THREAD

**Issue by kulame** [Ousret/charset_normalizer#237]
**Describe the bug**
```bash
(loader-py3.11) ➜  loader poetry add requests
Using version ^2.28.1 for requests

Updating dependencies
Resolving dependencies... (0.2s)

Because requests (2.28.1) depends on charset-normalizer (>=2,<3)
 and no versions of requests match >2.28.1,<3.0.0, requests (>=2.28.1,<3.0.0) requires charset-normalizer (>=2,<3).
So, because loader depends on both charset-normalizer (^3.0.0) and requests (^2.28.1), version solving failed.
```

**To Reproduce**
Give us the target text file. Host it somewhere with untouched encoding.

**Expected behavior**
make requests and charset_normalizer compatible

**Logs**
If applicable, add console outputs to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Linux, Windows or Mac]
 - Python version [e.g. 3.5]
 - Package version [eg. 2.0.0]

**Additional context**

**Comment by Ousret** [comment]
I understand the frustration you encountered but it is not in my power to solve this.
As I have seen, `requests` is working toward a new release that will update the version constraint to `>=2,<4`.

In the meantime pin charset-normalizer to 2.1.1.
