### ISSUE TITLE
[DETECTION] Cannot detect Indonesian language

### ISSUE THREAD

**Issue by lucemia** [Ousret/charset_normalizer#246]
**Notice**
I hereby announce that my raw input is not :
- Too small content (<=32 characters) as I do know that ANY charset detector heavily depends on content
- Encoded in a deprecated/abandoned encoding that is not even supported by my interpreter

**Provide the file**
A accessible way of retrieving the file concerned. Host it somewhere with untouched encoding.
[id.zip](https://github.com/Ousret/charset_normalizer/files/10163781/id.zip)

**Verbose output**
Using the CLI, run `normalizer -v ./my-file.txt` and past the result in here.

```
normalizer -v src/sdk/nlp/tests/text/id/10.txt 
2022-12-06 15:26:15,581 | INFO | ascii passed initial chaos probing. Mean measured chaos is 8.467000 %
2022-12-06 15:26:15,582 | INFO | ascii should target any language(s) of ['Latin Based']
2022-12-06 15:26:15,586 | INFO | We detected language [('English', 1.0), ('German', 0.9332), ('French', 0.9251)] using ascii
2022-12-06 15:26:15,586 | INFO | ascii is most likely the one. Stopping the process.
```

**Expected encoding**

All 40 attached files should be `Indonesian` as `Language`, but charset-normalizer returns `English` 

**Desktop (please complete the following information):**
 - OS: Mac
 - Python version: python 3.9
 - Package version [eg. 2.0.0]: 3.0.1

**Additional context**

**Comment by Ousret** [comment]
Hi,

Well, it isn't a bug in that case. I choose to disable the language detection when it is about `ASCII` and return 'English' as default. This was out of performance concerns, as ASCII is often predominant (json, etc..)

If you want to, use directly https://github.com/Ousret/charset_normalizer/blob/9b216b5cbf637f0e2470c24b5942afd9c0a8aa63/charset_normalizer/cd.py#L343

```python
from charset_normalizer.cd import coherence_ratio
```

I tested your files by adding a single non-ASCII characters in each, it seems to be OK.
