### ISSUE TITLE
[BUG] str(results.best()) will results in additional '\n' escape sequences

### ISSUE THREAD

**Issue by LeeFuuChang** [Ousret/charset_normalizer#264]
**Describe the bug**
reading using results.best and rewrite back into files will results in additional '\n' escape sequences
![image](https://user-images.githubusercontent.com/77952182/216228208-89bf8723-eb8e-44e1-9dd4-67f2bf3e1291.png)

**To Reproduce**
```python
from charset_normalizer import from_path

path = r"path ~ to ~ text ~ file"

results = from_path(path)

a = str(results.best())
with open(path, "r") as f:
    b = f.read()

with open("a.txt", "w") as f:
    f.write(a) # with addiitional newlines
with open("b.txt", "w") as f:
    f.write(b) # original file content

print(a == b) # False
```

**Expected behavior**
I expected it be be the same after rewriting

**Comment by Ousret** [comment]
Hello,

I understand the confusion, let me sort this out.
It is an operating system-specific issue on how or what the default parameters of `open` is. It is not related to charset-normalizer. And also, Python designed this function to follow the system's default settings.

On a recent Linux distro, this should not be reproducible. I suspect you are on Windows.


See

```python
import os
import locale

# check
print(os.linesep)
print(locale.getpreferredencoding())
# force utf-8 and specific newline character
open(fp, 'w', encoding='utf-8', newline='\n')
```

Hope that answer the question,

**Comment by Ousret** [comment]
Yes. Write bytes, not str.

The `open` function is bound to OS specifics when you pass a `str` to it.

```python

file_content = results.best().output("utf-16")
with open("example_exported.txt", "wb") as file:
    file.writelines(file_contents)

```

**Comment by Alexander-Wilms** [comment]
Thanks. In my use case I also need to manipulate (search and replace) the file contents. So I guess I can either convert it to bytes and write using `wb` or use `newline="\n"`
