### ISSUE TITLE
[Proposal] Unicode language space detection

### ISSUE THREAD

**Issue by DonaldTsang** [Ousret/charset_normalizer#27]
**Is your feature request related to a problem? Please describe.**
Yes, I am trying to create a filter to detect whether or not a string CAN be a part of a specific language. e.g.Italian should not have Greek or Cyrillic, or even Latin characters with diacritics.

**Describe the solution you'd like**
A regex-based or codepoint-based system to show what languages is expected to have what alphabet (or not). 

**Describe alternatives you've considered**
Creating my own regex

**Additional context**
It is used to filter image tags (information string consisting of one or few words) by language so that I can automatically detect languages that don't belong within a language.

**Comment by DonaldTsang** [comment]
https://github.com/Mimino666/langdetect/issues/66

**Comment by DonaldTsang** [comment]
There are data like https://www.unicode.org/cldr/charts/latest/summary/root.html  with "Characters in Use".

**Comment by Ousret** [comment]
This was integrated starting version 2.0
It does help to focus the "target" language(s) to be detected.
