### ISSUE TITLE
[BUG] Installing 3.1.0 via pip fails due to "HTTP error 403 Client Error: VirusFound"

### ISSUE THREAD

**Issue by SalttownUser** [Ousret/charset_normalizer#274]
**Describe the bug**

Installing version 3.1.0 in Windows 10 via pip 23.0.1 failes with this error message:

cmd: ` py -m pip install charset-normalizer==3.1.0`

```
Collecting charset-normalizer==3.1.0
  ERROR: HTTP error 403 while getting https://files.pythonhosted.org/packages/ad/83/994bfca99e29f1bab66b9248e739360ee70b5aae0a5ee488cd776501edbc/charset_normalizer-3.1.0-cp311-cp311-win_amd64.whl (from https://pypi.org/simple/charset-normalizer/) (requires-python:>=3.7.0)      
ERROR: Could not install requirement charset-normalizer==3.1.0 from https://files.pythonhosted.org/packages/ad/83/994bfca99e29f1bab66b9248e739360ee70b5aae0a5ee488cd776501edbc/charset_normalizer-3.1.0-cp311-cp311-win_amd64.whl because of HTTP error 403 Client Error: VirusFound for url: https://files.pythonhosted.org/packages/ad/83/994bfca99e29f1bab66b9248e739360ee70b5aae0a5ee488cd776501edbc/charset_normalizer-3.1.0-cp311-cp311-win_amd64.whl for URL https://files.pythonhosted.org/packages/ad/83/994bfca99e29f1bab66b9248e739360ee70b5aae0a5ee488cd776501edbc/charset_normalizer-3.1.0-cp311-cp311-win_amd64.whl (from https://pypi.org/simple/charset-normalizer/) (requires-python:>=3.7.0)
```

- Connection to pypi goes via a proxy server.
- Versions 2.x, 3.0.0 and 3.0.1 work fine.

**To Reproduce**
I think it is not as simple as installing 3.1.0 fails on every W10 system because of the small number of complains...

Migth have something to do with our anti virus solution checking the file.

**Expected behavior**
Installing the package should not fail.

**Logs**
If applicable, add console outputs to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows 10.0.19045 Build 19045
 - Python version: 3.11.0
 - Package version 3.1.0

**Comment by Ousret** [comment]
Hello,

While it is probably a false positive / falsely flagged by your protection I sent the report so it could be analyzed by experts. Action will be taken in case something come up.
Next time, use the security contact/procedure specified in the repo for anything related. https://github.com/Ousret/charset_normalizer/security/policy

Regards
