### ISSUE TITLE
[Proposal] Homoglyph handling

### ISSUE THREAD

**Issue by DonaldTsang** [Ousret/charset_normalizer#28]
**Is your feature request related to a problem? Please describe.**
There may be times where people use homoglyph fuzzing to avoid language detection

**Describe the solution you'd like**
A way to "normalize" the text such that accuracy can be enhanced.

**Describe alternatives you've considered**
- https://github.com/life4/homoglyphs (preferred)
- https://github.com/DavidJacobson/SafeText
- https://github.com/vhf/confusable_homoglyphs
- https://github.com/NebulousLabs/glyphcheck

**Comment by DonaldTsang** [comment]
More to read about https://github.com/life4/homoglyphs/issues/19

**Comment by Ousret** [comment]
After much consideration, this solution won't do homoglyph handling.
