### ISSUE TITLE
"Pure Python" no longer?

### ISSUE THREAD

**Issue by akx** [Ousret/charset_normalizer#310]
Multiple places claim that charset_normalizer is "pure Python", yet it definitely seems to have binary components (that [don't work for some folks](https://stackoverflow.com/questions/76715259/mach-o-file-but-is-an-incompatible-architecture-have-x86-64-need-arm64)).

Maybe those references ought to be fixed (and maybe the "wheel size" in the readme's comparison table should also be fixed, since it refers to the non-mypyc'd wheel).

If anything, it might be a good idea to inform users on how to install the non-mypyc'd wheel in the readme :)

**Comment by Ousret** [comment]
> Multiple places claim that charset_normalizer is "pure Python", yet it definitely seems to have binary components (that [don't work for some folks](https://stackoverflow.com/questions/76715259/mach-o-file-but-is-an-incompatible-architecture-have-x86-64-need-arm64)).

The "don't work for some folks" is somewhat incomplete.
What you refer to is not a problem with charset-normalizer and definitely not a problem with pip.

`This seems to be a bug in charset_normalizer. pip uninstall charset-normalizer; pip install chardet` It is not true.
Picking the right wheel is done through pip, and as far as I know, it works period.

It is available as pure Python, still, and ships with non-pure (mypyc compilation) within specific conditions.

> Maybe those references ought to be fixed (and maybe the "wheel size" in the readme's comparison table should also be fixed, since it refers to the non-mypyc'd wheel).

The term "fixed" is not right, but, yes, why not.

> If anything, it might be a good idea to inform users on how to install the non-mypyc'd wheel in the readme :)

The README is not meant for detailed and advanced usage. It is referenced in the documentation.
