### ISSUE TITLE
Allow running of the package via `python3 -m charset_normalizer -h`

### ISSUE THREAD

**Issue by DeflateAwning** [Ousret/charset_normalizer#315]
Here's how to implement that, as a commit on a similar package: https://github.com/chardet/chardet/commit/0e9b7bc20366163efcc221281201baff4100fe19

Not every enterprise system allows modifying the PATH/running binaries, so it's helpful to be able to run it as a module like this.

**Comment by Ousret** [comment]
I understand. Will look into it prior to the next minor release.

**Comment by DeflateAwning** [comment]
Awesome, super easy fix. You just have to add a `__main__.py` file, exactly as in that linked commit.

**Comment by DeflateAwning** [comment]
Why did you make it so you have to add the `.cli` suffix? People won't know that's required.

**Comment by Ousret** [comment]
Placing `__main__` in the root package level did not make much sense to me.
I don't see why executing module `charset_normalizer` should lead to the CLI. Philosophical point of view.
Executing submodule `cli` of charset_normalizer is more compelling.

The initial request was to bypass the PATH limitation you encountered and this should be sufficient.
It will be more documented so that users may find it more easily.

If you can present more arguments, I will review them of course.
Regards,

**Comment by DeflateAwning** [comment]
It's just the standard way to implement this; you make it so that calling the package with `python -m project_name <args>` works the same as `project_name <args>`. This is a UX change; not a project organization change. 

`chardet`, `dtrx`, `tt`, etc. all do it the way I'm describing

**Comment by Ousret** [comment]
> It's just the standard way to implement this;

Is there an accepted PEP I missed? If so, I'll comply.

> chardet, dtrx, tt, etc. all do it the way I'm describing

I know that, and it is not a good argument, unfortunately.
Dominant behavior isn't necessarily the right one.

**Comment by DeflateAwning** [comment]
You got me. I'll propose a new PEP. 

PEP 509: "The standard way to instantiate Python is to type `python_start_the_repl.yes_really_start_the_repl.repl_starter`. Why would anyone possibly want a concise thing to type in the terminal to start a script?

There's a reason the command is `cat` and not `concatenate`. There's a reason the command is called `python` and not `python_programming_language_interpretter`. 

You want a PEP that says conciseness is better? 

If you add an error message that looks like this, I guess I'll stop arguing with you.

```
$ python -m charset_normalizer -h
ERROR: Please call `python -m charset_normalizer.cli <args>`. If you're annoyed, please chime in at https://github.com/Ousret/charset_normalizer/issues/315.
```

**Comment by Ousret** [comment]
I understand the frustration.
Nevertheless, I can argue in favor of an opinion that differs from yours. You should definitely lower the sarcasm.

I understand the need for shortness, but the package name length itself won't help...

> Why would anyone possibly want a concise thing to type in the terminal to start a script?
Yes, it is supported. Through PATH, and defined entry-point. 

I'll give it another round of thinking later.

Regards,

**Comment by DeflateAwning** [comment]
:)
