### ISSUE TITLE
Wrong encoding detected for url

### ISSUE THREAD

**Issue by mcarans** [Ousret/charset_normalizer#32]
**Describe the bug**
It looks like charset_normalizer detects the wrong format.

**To Reproduce**
```
from urllib.request import urlopen
import chardet
import cchardet
import charset_normalizer
import magic

with magic.Magic() as m:
    rawdata = urlopen('https://api.acleddata.com/acled/read.csv?limit=0&terms=accept&iso=112').read()
    print(chardet.detect(rawdata))
    print(cchardet.detect(rawdata))
    print(charset_normalizer.detect(rawdata))
    print(m.id_buffer(rawdata))
```

**Expected behavior**
charset_normalizer detects cp932 which is a Japanese code page. However I don't see Japanese characters in the file. file -i, enca, chardet and cchardet think it is utf-8.

**Logs**
```
{'encoding': 'utf-8', 'confidence': 0.7525, 'language': ''}
{'encoding': 'UTF-8', 'confidence': 0.7524999976158142}
{'encoding': 'cp932', 'language': 'English', 'confidence': 0.9533799533799534}
UTF-8 Unicode text, with very long lines
```

**Desktop (please complete the following information):**
 - OS: [e.g. Linux, Windows or Mac] Linux
 - Python version [e.g. 3.5] 3.6

**Comment by Ousret** [comment]
Hi,

Sorry for the lack of answers. I never could retrieve the target resource.
Hopefully, later releases will serve you better.

Regards,
