### ISSUE TITLE
[BUG] Unable to force-reinstall on Windows while in use - >=3.0.0

### ISSUE THREAD

**Issue by carri0911** [Ousret/charset_normalizer#326]
**Describe the bug**
charset-normalizer >=3.0.0 unable to be --force-reinstalled while _in use_ (imported in a python script via the [requests package](https://pypi.org/project/requests/) in my case) on Windows.

**To Reproduce**
Install charset-normalizer, import charset-normalizer in test_script.py, run test_script.py. During runtime of script, run the following command
>python -m pip install --force-reinstall --upgrade charset-normalizer

**Expected behavior**
Package is able to be reinstalled, which is what occurs on versions <3.0.0

**Logs**
`Attempting uninstall: charset-normalizer  
    Found existing installation: charset-normalizer 3.2.0  
    Uninstalling charset-normalizer-3.2.0:  
      Successfully uninstalled charset-normalizer-3.2.0  
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: '...\\Python\\Python311\\Lib\\site-packages\\~harset_normalizer\\md.cp311-win_amd64.pyd'  
Consider using the --user option or check the permissions.`

**Desktop:**
 - OS: Windows (Haven't had the same issue on Linux or Mac)
 - Python version 3.11.4
 - Package version: >3.0.0

**Additional context**
Python reinstalls have been attempted, different versions and using the `--user` option. 
Same issue occurred on both Win 11 & Win 10 devices.
Also attempted installing and running in a venv, same issue.

**Comment by Ousret** [comment]
As far as I know, what you encountered is either a limitation of your file system (max path length), or your anti-virus, or the company's excessive rules on what you can install.

Unfortunately, I cannot do anything in all of the given cases.

If you have reached the tight limit on how long a path could be. Please refer to https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry
for support and solutions.

If it is not about the path length, try:

`pip install requests --no-binary charset-normalizer`

Regards,

**Comment by Ousret** [comment]
I may have misunderstood your initial request.

> charset-normalizer >=3.0.0 unable to be --force-reinstalled while in use

You should not do that. Ever.
If your program is up and running, doing this is certainly unwise and unpredictable.

Regards,
