### ISSUE TITLE
[BUG] prettytable 2.x support

### ISSUE THREAD

**Issue by jayvdb** [Ousret/charset_normalizer#35]
The latest release pins prettytable <2  This makes it incompatible with prettyable distributed by openSUSE, and likely other vendors also.  There were not too many changes in prettytable 2.x ; it should be possible to support 1.x and 2.x

**Comment by Ousret** [comment]
Hi,

prettytable dropped the support for python 3.5. That is the only concern I have. I’ll look into this ASAP.

**Comment by Ousret** [comment]
It's done. Thank you for your vigilance.
