### ISSUE TITLE
IS this code reachable?

### ISSUE THREAD

**Issue by chris-ha458** [Ousret/charset_normalizer#350]
https://github.com/Ousret/charset_normalizer/blob/58f69f76983fc2042b4f47037c02d2d74ecec2cc/charset_normalizer/models.py#L58C16-L58C78

The outer if would mean that `coherence_difference > 0.02`
The inner if would require that `self.coherence == other.coherence`, in other words coherence_difference == 0.0

Am I misunderstanding the code? or was there a mistake here?

**Comment by Ousret** [comment]
Good catch.
This piece of code was intended for some edge cases. And could not have possibly run.
I issued a fix.
