### ISSUE TITLE
Underscore or Dash when pip installing?

### ISSUE THREAD

**Issue by DannyDannyDanny** [Ousret/charset_normalizer#37]
**Is your feature request related to a problem? Please describe.**
A red-flag went of in my head when I saw the inconsistent package spelling (`-` vs `_`):

PyPi page:
![image](https://user-images.githubusercontent.com/16453674/110794584-2f861400-8276-11eb-915c-66b3e193db19.png)

ReadTheDocs:
![image](https://user-images.githubusercontent.com/16453674/110794736-55abb400-8276-11eb-97c5-5898655d49ff.png)

ReadMe.md
![image](https://user-images.githubusercontent.com/16453674/110794816-6e1bce80-8276-11eb-95f2-b0ddb4b32b9f.png)

**Describe the solution you'd like**
Consistency. Either `pip install charset-normalizer` or `pip install charset_normalizer`. I have no preference.

**Additional context**
There's a lot of nasty malware packages out there... ([src](https://twitter.com/DataNerdery/status/1366263351685226499)). Inconsistency and names that are slightly are a bad sign 🔥 
![image](https://user-images.githubusercontent.com/16453674/110795359-05812180-8277-11eb-88a4-42bc5f603488.png)

**Comment by Ousret** [comment]
Hi @DannyDannyDanny 

Thanks for the report. 
Indeed the official package name is `charset_normalizer`. But pypi seems to ignore `_` and replace it immediately with `-`.

So the correct way to install it is `pip install charset-normalizer`. There is a good chance that they are aware of the situation and apparently fixed it. Correct me if I am wrong.

Regards,
