### ISSUE TITLE
[Proposal] allow to disable language detection

### ISSUE THREAD

**Issue by milahu** [Ousret/charset_normalizer#389]
the language detection gives too many false results to be usable

im parsing millions of subtitles files from opensubtitles.org
and for example for czech subtitles
charset_normalizer returns the languages Czech or Slovak or Croatian
because these are similar languages, they all are slavic languages
but the expected language is always Czech
and if the language is wrong, then its for example English, which is clearly different

since i dont use charset_match.language or charset_match.languages
i would like to disable the language detection feature
assuming that charset_normalizer.from_bytes would run faster

maybe even disable language-detection by default...
but i guess the language detection is required to guess the encoding, right?
(then i hope this works with mixed-languages texts...)

for a better language detection, i would use [argostranslate.apis.LibreTranslateAPI.detect](https://argos-translate.readthedocs.io/en/latest/source/argostranslate.html#argostranslate.apis.LibreTranslateAPI.detect)
which uses 59 language models weighing 6 GB
so language-detection is much more complex than encoding-detection

also [the docs](https://charset-normalizer.readthedocs.io/en/latest/api.html#charset_normalizer.models.CharsetMatch.languages) say

> property languages: List[str]
>
> Return the complete list of possible languages found in decoded sequence. **Usually not really useful.**

**Comment by Ousret** [comment]
I understand the frustration you are encountering.

As you have guessed it we rely on the "language/coherence" detector to help with the final decision.
Think of it as a way to determine "Yes, that decoded content show clear sign of intelligence" meaning that it makes sense.

We just cannot disable it per default. The confidence is going to drop.

See https://github.com/Ousret/charset_normalizer/issues/200 for more

You can help by improving https://github.com/Ousret/charset_normalizer/blob/3afb28de46cad4348fd48b1e9836e58ed5c4b617/charset_normalizer/constant.py#L559 
The letter ranking is most likely updatable and the algorithm behind can most certainly be improved without too much performance loss.

Regards,
