### ISSUE TITLE
[Proposal] Vendoring charset-normalizer in pip

### ISSUE THREAD

**Issue by bluetech** [Ousret/charset_normalizer#456]
While looking into pip's startup time, I found that replacing chardet with charset-normalizer improves things. pip has a [policy](https://pip.pypa.io/en/stable/development/vendoring-policy/) of vendoring its dependencies, so I'd like to propose to pip to change its vendoring from chardet to charset-normalizer.

Before I do it, I'd like to ask if you are OK with this?

See pip discussion here: https://github.com/pypa/pip/issues/4768#issuecomment-2062541405

**Comment by Ousret** [comment]
I am OK with this.

While speaking performances, maybe in a not too distant future, pip may consider replacing requests for niquests.

Regards,

**Comment by Ousret** [comment]
qh3 is optional.
