### ISSUE TITLE
[Proposal] Line endings in readme.md

### ISSUE THREAD

**Issue by frenzymadness** [Ousret/charset_normalizer#66]
Would it be possible to change line endings in README.md from Windows CRLF to Unix-style LF? You can use `dos2unix` utility for that.

**Comment by Ousret** [comment]
Hi @frenzymadness 

I have issued some commits using the NT platform. I will review all the files whenever possible. I'd rather have LF line ending.
Would you verify the entire repository? Even better, if you could issue a PR.

Thanks.

**Comment by frenzymadness** [comment]
Almos all files converted in #67

**Comment by Ousret** [comment]
Answered by #67
