### ISSUE TITLE
Comparison with other products

### ISSUE THREAD

**Issue by DonaldTsang** [Ousret/charset_normalizer#7]
The main concern are:
- Language and encoding coverage
- Speed and memory usage

The list:
- https://github.com/polygonplanet/encoding.js (JS)
- https://github.com/douban/PyCharlockHolmes (Python + ICU)
  - https://github.com/siuying/charlock_holmes-jruby (Multilingual)
- https://github.com/adah1972/tellenc (C++)
- https://github.com/hydra13142/chardet (Go)
- https://github.com/seangarner/node-stream-mmmagic (JS)
- https://github.com/cv/encoding-detector (Python, not mature?)
- https://github.com/LasseRafn/php-string-script-language (PHP)
- https://github.com/hozumi/clj-det-enc (Clojure)
- Others not included in this list

**Comment by Ousret** [comment]
Thank you. For now the main concern should be around Python.

**Comment by DonaldTsang** [comment]
@Ousret I do support Python as the language, I am referring to feature concerns like coverage and performance tables on the ReadME.

**Comment by Ousret** [comment]
Just added supported encoding list through docs and README.

**Comment by DonaldTsang** [comment]
For a note on possible list of encodings:
- https://github.com/polygonplanet/encoding.js#available-encodings
- https://github.com/siuying/charlock_holmes-jruby/blob/master/spec/encoding_detector_spec.rb#L66
- https://github.com/adah1972/tellenc#overview
- https://github.com/hydra13142/chardet#chardet
- https://github.com/cv/encoding-detector/tree/master/chardet

And for languages https://github.com/LasseRafn/php-string-script-language#supported-scripts
